from argparse import ArgumentParser, Namespace, _SubParsersAction
from time import struct_time as struct_time
from typing import Any

description: str

class TransInvoker:
    TIME_TO_STR: int = ...
    STR_TO_TIME: int = ...
    date: Any = ...
    time: Any = ...
    cmd: Any = ...
    time_num: Any = ...
    use_second: Any = ...
    date_only: Any = ...
    run_method: Any = ...
    def __init__(self, **kw: Any) -> None: ...
    def do_run(self) -> None: ...
    def _do_time_to_str(self) -> None: ...
    def _do_str_to_time(self) -> None: ...

def genParser() -> ArgumentParser: ...
def setOptionArg(pp: ArgumentParser) -> Any: ...
def injTimeToStrParser(p: _SubParsersAction) -> Any: ...
def injStrToTimeParser(p: _SubParsersAction) -> Any: ...
def parseInput(nn: Namespace) -> TransInvoker: ...
